### ISSUE TITLE
Blank Controller tab/Program possibly glitched

### ISSUE THREAD

**Issue by Oneshinw3** [x360ce/x360ce#1158]
Its completely blank. I don't understand why this is happening when it was working fine 8/31.

![Capture](https://user-images.githubusercontent.com/38709080/92200301-20de2080-ee3f-11ea-9f99-915ddaffdafe.PNG)

**Comment by YouKnow-sys** [comment]
i have same problem
no matter how many time i close and reopen it...
it just blank (i also try with admin permission)

**Comment by EJocys** [comment]
Could you check c:\ProgramData\X360CE\Errors\ folder, please, and see if it contains error report files (FCE_*.htm)?
If "Yes", then could you send couple of most recent *.htm files to support@x360ce.com.

I've released new version of X360CE Today (version 4.13.41.0). You can download it  from:
https://github.com/x360ce/x360ce/releases

**Comment by nvkex** [comment]
I installed the latest update and am still having the same issue.

**Comment by nvkex** [comment]
This seems to work for me.
1 - Go to this folder: C:\ProgramData\X360CE.
2 - Delete all folders inside expect Errors folder.
3 - Restart the emulator.

**Comment by EvoJocys** [comment]
Sorry for the six years late answer. The project was dormant from 2020 and has been active again since August 2026.

Fixed. From the changelog:

4.18.40 — Fixed: Controller picture stayed grey, or moved while nothing was touched.
4.17.50 — Changed: Controller picture drawn with Windows Forms; memory use drops.

Download: https://github.com/x360ce/x360ce/releases

Closing as part of a tracker clean-up after the 4.21 release. If it still happens on 4.21, reopen this issue with the version and what you see.
