### ISSUE TITLE
Guide button map not work fine in last version

### ISSUE THREAD

**Issue by reproteq** [x360ce/x360ce#1203]
Guide button map not work fine in last version
When press button guide functions normaly
is same press button game bar for record , this not normaly function.
example cant see map in fortnite 
i use ps5 dualsense

Is posible assign key "M" in this button 14 guide ?
is option for solved issue

**Comment by EJocys** [comment]
@reproteq Thank you for reporting. Updated x360ce to use different virtual code to simulate Guide button {7}  instead of {LWin}{G}

v4.17.13.0 (2020-11-15)
- Fixed: Guide button virtual key code fixed.

You can assign various button combinations to Guide button.
For letter M just replace {7} with {M}

All codes are here: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=net-5.0


![image](https://user-images.githubusercontent.com/11958537/99190906-481b6d00-2761-11eb-94af-9ed68c3d0c7d.png)

**Comment by reproteq** [comment]
oooohh yeahhh now work fine
thanks alot!

**Comment by hifihedgehog** [comment]
This is still an issue because it is not working like a true guide button. XOutput uses the same ViGEm interface as x360ce and it simulates a true Guide button, not a virtual key. See code here:

https://github.com/csutorasa/XOutput/blob/f784c48091f3657f8ecbcd9f87901756ff4967c7/XOutput.Emulation/ViGEm/VigemXboxDevice.cs

I just created an issue #1223 related to this.

**Comment by hifihedgehog** [comment]
If the Guide button is actually working, it should register as button B11 if I am not mistaken on gamepad-tester.com.

**Comment by hifihedgehog** [comment]
Please add the following line of code to **x360ce/x360ce.App.Beta/Common/DInput/DInputHelper.Step5.VirtualDevices.cs** at **line 146**. It should enable true Guide button functionality. It is cool that you can use the keyboard mapping instead of Guide, but some games expect a true Guide button. Please fix this.

> report.SetButtonState(Xbox360Buttons.Guide, n.Buttons.HasFlag(GamepadButtonFlags.Guide));

See here: https://github.com/x360ce/x360ce/blob/f295e72ea242ca180b5a09389d63eb3fd503d995/x360ce.App.Beta/Common/DInput/DInputHelper.Step5.VirtualDevices.cs#L146
